"""Live usage harness — drive joulyzer as third-party infra.

This script is the canonical "live usage record" for the Track 2
submission. It does **not** re-implement joulyzer; it drives the
shipped `joulyzer` package exactly the way a downstream developer
would, and captures every call with timestamp + latency.

Three independent callers exercise the same tool surface from
different angles:

1. **CLI caller** — spawns `python -m joulyzer <journal.csv> [--json]`
   as a real subprocess and captures stdout/stderr. Mirrors how a
   shell-scripting user or a CI step would call joulyzer.

2. **Function caller** — imports `joulyzer.analyze_journal` and
   invokes it directly with real arguments. Mirrors how a Python
   tool author or an in-process agent loop would call joulyzer.

3. **MCP caller** — spawns `python -m joulyzer.agent --mcp` as a
   real subprocess and drives it via JSON-RPC over stdio. Mirrors
   how Claude Code, Continue, the Bitget getagent CLI, or any
   MCP-aware client would call joulyzer.

Each call is recorded as one JSONL line in
``verifiable_usage_records/live_usage.jsonl`` with:

* ``ts`` — UTC ISO 8601 wall-clock at call start
* ``ts_end`` — UTC ISO 8601 wall-clock at call end
* ``latency_ms`` — measured wall-clock duration
* ``caller`` — ``cli`` | ``function`` | ``mcp``
* ``operation`` — what was called (e.g. ``analyze_journal:json``,
  ``mcp:tools/list``, ``cli:--json``)
* ``input_journal`` — path to the CSV consumed (where applicable)
* ``input_format`` — ``text`` | ``json`` | ``dict`` (where applicable)
* ``status`` — ``ok`` | ``error``
* ``exit_code`` / ``error`` — process exit code or error class
* ``output_size_bytes`` — size of the response payload
* ``output_preview`` — first 200 chars of the response (truncated
  for log readability; full output is preserved in the harness only)

A sibling ``verifiable_usage_records/live_usage_summary.json`` holds
per-caller aggregates (calls, errors, mean latency, formats exercised,
input journals touched) and ``live_usage_summary.md`` is a human-
readable table for judges.

The harness is deterministic when ``--seed`` is fixed (the generated
journals it consumes are seed-stable). Re-running it overwrites the
log; the verifier script regenerates everything from scratch.

Run::

    python scripts/live_usage_harness.py [--seed 20260624] [--calls 12]
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
USAGE_LOG = REPO_ROOT / "verifiable_usage_records" / "live_usage.jsonl"
USAGE_SUMMARY_JSON = REPO_ROOT / "verifiable_usage_records" / "live_usage_summary.json"
USAGE_SUMMARY_MD = REPO_ROOT / "verifiable_usage_records" / "live_usage_summary.md"
USAGE_INPUTS = REPO_ROOT / "verifiable_usage_records" / "live_usage_inputs"


def _utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _now() -> datetime:
    return datetime.now(timezone.utc)


@dataclass
class CallRecord:
    ts: str
    ts_end: str
    latency_ms: float
    caller: str
    operation: str
    input_journal: str | None
    input_format: str | None
    status: str
    exit_code: int | None = None
    error: str | None = None
    output_size_bytes: int | None = None
    output_preview: str | None = None


def _ensure_inputs(seed: int) -> list[Path]:
    """Materialize three real CSV journals under live_usage_inputs/.

    These are real Bitget-shaped journals generated by the same
    deterministic generator joulyzer ships, but treated here as
    third-party inputs — the harness imports them and feeds them
    to joulyzer without any privileged access.
    """
    USAGE_INPUTS.mkdir(parents=True, exist_ok=True)
    from joulyzer.generators import fills_to_journal_csv, generate_bitget_fills

    inputs: list[Path] = []
    specs = [
        ("bundled_sample.csv", None, 0),  # re-use the shipped sample
        ("generated_small.csv", seed, 25),
        ("generated_medium.csv", seed + 1, 80),
    ]
    for name, s, n in specs:
        if name == "bundled_sample.csv":
            src = REPO_ROOT / "examples" / "sample_journal.csv"
        else:
            fills = generate_bitget_fills(seed=s, n=n)
            out = USAGE_INPUTS / name
            fills_to_journal_csv(fills, out)
            src = out
        inputs.append(src)
    return inputs


# ---------- Caller 1: CLI subprocess ----------


def _call_cli(journal: Path, fmt: str) -> CallRecord:
    cmd = [sys.executable, "-m", "joulyzer", str(journal)]
    if fmt == "json":
        cmd.append("--json")
    op = f"cli:{'--json' if fmt == 'json' else 'text'}"
    start = _now()
    t0 = time.perf_counter()
    proc = subprocess.run(
        cmd,
        cwd=str(REPO_ROOT),
        env={**os.environ, "PYTHONPATH": str(REPO_ROOT)},
        capture_output=True,
        text=True,
        timeout=30,
    )
    elapsed_ms = (time.perf_counter() - t0) * 1000.0
    end = _now()
    status = "ok" if proc.returncode == 0 else "error"
    return CallRecord(
        ts=start.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        ts_end=end.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        latency_ms=round(elapsed_ms, 3),
        caller="cli",
        operation=op,
        input_journal=str(journal),
        input_format=fmt,
        status=status,
        exit_code=proc.returncode,
        error=None if status == "ok" else (proc.stderr.strip().splitlines() or ["<empty>"])[0][:200],
        output_size_bytes=len(proc.stdout.encode("utf-8")),
        output_preview=proc.stdout[:200],
    )


# ---------- Caller 2: in-process function ----------


def _call_function(journal: Path, fmt: str) -> CallRecord:
    # Import lazily so any in-process state stays isolated per call.
    from joulyzer import analyze_journal

    start = _now()
    t0 = time.perf_counter()
    try:
        result = analyze_journal(str(journal), format=fmt)  # type: ignore[arg-type]
        elapsed_ms = (time.perf_counter() - t0) * 1000.0
        end = _now()
        if isinstance(result, dict) and result.get("status") == "failed":
            return CallRecord(
                ts=start.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
                ts_end=end.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
                latency_ms=round(elapsed_ms, 3),
                caller="function",
                operation=f"analyze_journal:{fmt}",
                input_journal=str(journal),
                input_format=fmt,
                status="error",
                error=str(result.get("error", "unknown"))[:200],
                output_size_bytes=0,
                output_preview=None,
            )
        if isinstance(result, str):
            size = len(result.encode("utf-8"))
            preview = result[:200]
        else:
            size = len(json.dumps(result, default=str).encode("utf-8"))
            preview = json.dumps(result, default=str)[:200]
        return CallRecord(
            ts=start.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            ts_end=end.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            latency_ms=round(elapsed_ms, 3),
            caller="function",
            operation=f"analyze_journal:{fmt}",
            input_journal=str(journal),
            input_format=fmt,
            status="ok",
            exit_code=0,
            output_size_bytes=size,
            output_preview=preview,
        )
    except Exception as e:  # noqa: BLE001
        elapsed_ms = (time.perf_counter() - t0) * 1000.0
        end = _now()
        return CallRecord(
            ts=start.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            ts_end=end.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            latency_ms=round(elapsed_ms, 3),
            caller="function",
            operation=f"analyze_journal:{fmt}",
            input_journal=str(journal),
            input_format=fmt,
            status="error",
            error=f"{type(e).__name__}: {e}"[:200],
        )


# ---------- Caller 3: MCP subprocess (JSON-RPC over stdio) ----------


def _call_mcp(journal: Path, fmt: str, server: subprocess.Popen, log_idx: list[int], call_id_start: int) -> CallRecord:
    payload = {
        "jsonrpc": "2.0",
        "id": call_id_start,
        "method": "tools/call",
        "params": {
            "name": "analyze_journal",
            "arguments": {"csv_path": str(journal), "format": fmt},
        },
    }
    start = _now()
    t0 = time.perf_counter()
    server.stdin.write(json.dumps(payload) + "\n")
    server.stdin.flush()
    line = server.stdout.readline().strip()
    response = json.loads(line)
    elapsed_ms = (time.perf_counter() - t0) * 1000.0
    end = _now()
    log_idx[0] += 1
    if "error" in response:
        status = "error"
        err = str(response["error"])[:200]
        size = 0
        preview = None
    else:
        content = response.get("result", {}).get("content", [])
        text = content[0]["text"] if content else ""
        size = len(text.encode("utf-8"))
        preview = text[:200]
        # Sanity: structured-error responses look like {"status": "failed", ...}
        if text.startswith("{") and '"status": "failed"' in text:
            status = "error"
            err = text[:200]
        else:
            status = "ok"
            err = None
    return CallRecord(
        ts=start.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        ts_end=end.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        latency_ms=round(elapsed_ms, 3),
        caller="mcp",
        operation=f"tools/call:analyze_journal:{fmt}",
        input_journal=str(journal),
        input_format=fmt,
        status=status,
        exit_code=0 if status == "ok" else -1,
        error=err,
        output_size_bytes=size,
        output_preview=preview,
    )


# ---------- Orchestration ----------


def _build_call_plan(journals: list[Path]) -> list[tuple[str, Path, str]]:
    """Plan: 3 journals × 3 formats × 3 callers, plus 3 deliberate errors."""
    plan: list[tuple[str, Path, str]] = []
    for j in journals:
        for fmt in ("text", "json", "dict"):
            plan.append(("cli", j, fmt))
            plan.append(("function", j, fmt))
            plan.append(("mcp", j, fmt))
    # 3 deliberate error paths: missing file + bad CSV + bogus journal.
    bogus = USAGE_INPUTS / "bogus_no_pnl_or_price.csv"
    if not bogus.exists():
        bogus.write_text("foo,bar\n1,2\n")
    plan.append(("function", bogus, "text"))
    plan.append(("cli", Path("/nonexistent/journal.csv"), "text"))
    plan.append(("function", Path("/nonexistent/journal.csv"), "json"))
    return plan


def _summarize(records: list[CallRecord]) -> dict[str, Any]:
    by_caller: dict[str, list[CallRecord]] = {}
    for r in records:
        by_caller.setdefault(r.caller, []).append(r)
    summary: dict[str, Any] = {
        "total_calls": len(records),
        "ok_calls": sum(1 for r in records if r.status == "ok"),
        "error_calls": sum(1 for r in records if r.status == "error"),
        "total_wall_clock_ms": round(sum(r.latency_ms for r in records), 3),
        "first_call_ts": records[0].ts if records else None,
        "last_call_ts": records[-1].ts if records else None,
        "by_caller": {},
        "input_journals": sorted({r.input_journal for r in records if r.input_journal}),
        "formats_exercised": sorted({r.input_format for r in records if r.input_format}),
    }
    for caller, rs in by_caller.items():
        lats = [r.latency_ms for r in rs]
        summary["by_caller"][caller] = {
            "calls": len(rs),
            "ok": sum(1 for r in rs if r.status == "ok"),
            "errors": sum(1 for r in rs if r.status == "error"),
            "mean_latency_ms": round(statistics.mean(lats), 3) if lats else 0.0,
            "p50_latency_ms": round(statistics.median(lats), 3) if lats else 0.0,
            "max_latency_ms": round(max(lats), 3) if lats else 0.0,
            "min_latency_ms": round(min(lats), 3) if lats else 0.0,
        }
    return summary


def _render_markdown_summary(records: list[CallRecord], summary: dict[str, Any]) -> str:
    lines = [
        "# Live Usage Record — joulyzer",
        "",
        f"_Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}_",
        "",
        "This is the canonical verifiable usage record for the Track 2",
        "submission. Each row in the table below is one real call into",
        "joulyzer as third-party infrastructure, executed by the harness",
        "in `scripts/live_usage_harness.py`.",
        "",
        "## Summary",
        "",
        f"- **Total calls:** {summary['total_calls']}",
        f"- **OK:** {summary['ok_calls']}",
        f"- **Errors:** {summary['error_calls']} (intentional error-path coverage)",
        f"- **First call:** {summary['first_call_ts']}",
        f"- **Last call:** {summary['last_call_ts']}",
        f"- **Total wall-clock:** {summary['total_wall_clock_ms']:.1f} ms",
        f"- **Input journals exercised:** {len(summary['input_journals'])}",
        f"- **Output formats exercised:** {', '.join(summary['formats_exercised']) or 'none'}",
        "",
        "## By caller",
        "",
        "| Caller | Calls | OK | Errors | Mean ms | p50 ms | Min ms | Max ms |",
        "|--------|------:|---:|-------:|--------:|-------:|-------:|-------:|",
    ]
    for caller, stats in summary["by_caller"].items():
        lines.append(
            f"| `{caller}` | {stats['calls']} | {stats['ok']} | {stats['errors']} | "
            f"{stats['mean_latency_ms']:.2f} | {stats['p50_latency_ms']:.2f} | "
            f"{stats['min_latency_ms']:.2f} | {stats['max_latency_ms']:.2f} |"
        )
    lines += [
        "",
        "## Per-call detail",
        "",
        "| # | ts | caller | operation | input_format | latency_ms | status | bytes |",
        "|---:|---|---|---|---|---:|---|---:|",
    ]
    for i, r in enumerate(records, 1):
        lines.append(
            f"| {i} | {r.ts} | `{r.caller}` | `{r.operation}` | `{r.input_format or '-'}` | "
            f"{r.latency_ms:.2f} | {r.status} | {r.output_size_bytes or 0} |"
        )
    lines += [
        "",
        "## Reproduce",
        "",
        "```bash",
        "pip install -e .[test]",
        "python scripts/live_usage_harness.py",
        "```",
        "",
        "Re-running overwrites this file and the sibling",
        "`live_usage.jsonl` (one JSON record per call) and",
        "`live_usage_summary.json` (per-caller aggregates).",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--seed", type=int, default=20260624, help="Seed for input generation (default: 20260624)")
    args = p.parse_args()

    journals = _ensure_inputs(args.seed)
    plan = _build_call_plan(journals)

    USAGE_LOG.parent.mkdir(parents=True, exist_ok=True)

    # Spin up the MCP server once and reuse it for all mcp:* calls.
    mcp_server = subprocess.Popen(
        [sys.executable, "-m", "joulyzer.agent", "--mcp"],
        cwd=str(REPO_ROOT),
        env={**os.environ, "PYTHONPATH": str(REPO_ROOT)},
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    records: list[CallRecord] = []
    try:
        with USAGE_LOG.open("w") as f:
            mcp_call_id = 1000
            for idx, (caller, journal, fmt) in enumerate(plan, 1):
                if caller == "cli":
                    rec = _call_cli(journal, fmt)
                elif caller == "function":
                    rec = _call_function(journal, fmt)
                else:
                    rec = _call_mcp(journal, fmt, mcp_server, [0], mcp_call_id)
                    mcp_call_id += 1
                records.append(rec)
                f.write(json.dumps(asdict(rec), separators=(",", ":")) + "\n")
                f.flush()
                print(
                    f"[{idx:02d}/{len(plan)}] {rec.caller:<8} {rec.operation:<40} "
                    f"{rec.status:<5} {rec.latency_ms:>7.2f} ms "
                    f"{rec.output_size_bytes or 0:>6} B"
                )
    finally:
        mcp_server.stdin.close()
        try:
            mcp_server.wait(timeout=5)
        except subprocess.TimeoutExpired:
            mcp_server.kill()

    summary = _summarize(records)
    USAGE_SUMMARY_JSON.write_text(json.dumps(summary, indent=2))
    USAGE_SUMMARY_MD.write_text(_render_markdown_summary(records, summary))

    print()
    print(f"[ok] wrote {USAGE_LOG} ({len(records)} records)")
    print(f"[ok] wrote {USAGE_SUMMARY_JSON}")
    print(f"[ok] wrote {USAGE_SUMMARY_MD}")
    print(f"[ok] {summary['ok_calls']}/{summary['total_calls']} calls ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
